Jhaas/wglc 202404
mjethanandani/bfd-secure-sequence-numbers pull request #19
Opened 2024-04-29 22:47 UTC by jhaas-pfrc

Proposed edits to address open issues for next version targeting WGLC.

2024-04-30 00:08 UTC, mjethanandani requested changes

2024-04-30 00:08 UTC, mjethanandani commented on draft/Makefile
> +next_ver ?= 14
The next_ver is determined by the git tag that is created locally in the repo. Something I should document in README.

For example if you do the following:

git tag draft-ietf-bfd-secure-sequence-numbers-13

it will take the number 13 and do +1 to determine the next_ver.

2024-04-30 17:39 UTC, jhaas-pfrc commented on draft/Makefile
> +next_ver ?= 14
I seem to have to rediscover this about once a year when you've not done the underlying tagging. :-)

The headache with the process is that I would expect the tag to be run on the master branch at the time of publication.  Instead, here we've had creeping branches as the active work one.

As best I can tell, there are no tags in this repository.

What did you want to do about this?

2024-05-01 22:50 UTC, mjethanandani commented on draft/Makefile
> +next_ver ?= 14
The tags are independent of the branch you are working on. I have submitted a separate PR on how to push/pull down tags from the remote.

2024-05-01 22:51 UTC, mjethanandani commented on draft/Makefile
> +next_ver ?= 14
And I have pushed all the tags I had to the remote.

2024-05-01 23:59 UTC, mjethanandani approved these changes

2024-05-02 00:00 UTC, merged